---
- hosts: all
  become: true
  vars:
    apache_port: 80
    mysql_root_password: changeme
  tasks:
    - name: Install Apache web server
      package:
        name: httpd
        state: present

    - name: Install PHP
      package:
        name: php
        state: present

    - name: Install MySQL server
      package:
        name: mariadb-server
        state: present

    - name: Configure Apache to listen on the specified port
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen\s+.*'
        line: 'Listen {{ apache_port }}'

    - name: Start Apache web server
      service:
        name: httpd
        state: started

    - name: Start MySQL server
      service:
        name: mariadb
        state: started

    - name: Set root password for MySQL
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        host: localhost
